name: Hotel Inventory Update

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 最新版に変更

      - name: Set up Python
        uses: actions/setup-python@v5 # ここが間違っていました
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install gspread google-auth requests

      - name: Run script
        env:
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: python main.py
